### ISSUE TITLE
Missing module on NPM

### ISSUE THREAD

**Issue by verticalhost** [cconley717/MoarTube-Client#4]
Hi , 
After sending : npm i @moartube/moartube-client 
It's looks like some module is missing. 

![image](https://github.com/MoarTube/MoarTube-Client/assets/100486259/7574d65c-02f0-4756-9237-b9b7955cd107)

**Comment by cconley717** [comment]
I'm able to install the latest npm for the MoarTube Client and it is working normally. I'll investigate further.

**Comment by cconley717** [comment]
What Node.js version are you running? It appears your Node.js version is out of date. MoarTube was built with Node.js v20.  Please report back if upgrading your Node.js version resolves the issue.

**node -v** at the command line will output the version.

**Comment by verticalhost** [comment]
Good no prob. 
Thanks for this. 
Will it be possible in future to allowed others register on platform or for moment it's only like personnal website without registration for other user

**Comment by cconley717** [comment]
Anyone can post videos on the front page. No account needed. You are able to do this now. This is referred to as "indexing" your video. Anyone can do this. The video is linked to on the front page and when clicked it goes to your node.

https://moartube-node-chris.com/watch?v=DKrEhUuKgmp

**Comment by cconley717** [comment]
I think I misunderstood. Are you asking if it is possible to have more than one account for the node? If so, then for the moment, it's personal without registration for other users.
